export enum NotificationServiceCommands {
  GET_LIST_BY_PAGINATION = 'NOTIFICATION_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'NOTIFICATION_GET_ALL_LIST',
  GET_BY_ID = 'NOTIFICATION_GET_BY_ID',
  CREATE = 'NOTIFICATION_CREATE',
  CREATED = 'NOTIFICATION_CREATED',
  UPDATE = 'NOTIFICATION_UPDATE',
  SENT_NOTIFICATION = 'NOTIFICATION_SENT',
  DELETE = 'NOTIFICATION_DELETE',
  RESTORE = 'NOTIFICATION_RESTORE',
}
