export enum UserServiceCommands {
  GET_LIST_BY_PAGINATION = 'USER_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'USER_GET_ALL_LIST',
  GET_BY_ID = 'USER_GET_BY_ID',
  GET_ME_BY_ID = 'USER_GET_ME_BY_ID',
  CREATE = 'USER_CREATE',
  CREATED = 'USER_CREATED',
  UPDATE = 'USER_UPDATE',
  DELETE = 'USER_DELETE',
  RESTORE = 'USER_RESTORE',
  LOG_IN = 'USER_LOG_IN',
  CHECK_PERMISSION = 'USER_CHECK_PERMISSION',
}
