export enum siteStatisticsCommands {
  GET_LIST_BY_PAGINATION = 'SITE_STATISTICS_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'SITE_STATISTICS_GET_ALL_LIST',
  GET_BY_ID = 'SITE_STATISTICS_GET_BY_ID',
  CREATE = 'SITE_STATISTICS_CREATE',
  CREATED = 'SITE_STATISTICS_CREATED',
  UPDATE = 'SITE_STATISTICS_UPDATE',
  DELETE = 'SITE_STATISTICS_DELETE',
  RESTORE = 'SITE_STATISTICS_RESTORE',
}
