export enum SectionServiceCommands {
  GET_LIST_BY_PAGINATION = 'SECTION_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'SECTION_GET_ALL_LIST',
  GET_BY_ID = 'SECTION_GET_BY_ID',
  CREATE = 'SECTION_CREATE',
  CREATED = 'SECTION_CREATED',
  UPDATE = 'SECTION_UPDATE',
  DELETE = 'SECTION_DELETE',
  RESTORE = 'SECTION_RESTORE',
}
