export enum FirebaseServiceCommands {
    GET_LIST_BY_PAGINATION = 'FIREBASE_GET_LIST_BY_PAGINATION',
    GET_ALL_LIST = 'FIREBASE_GET_ALL_LIST',
    GET_BY_ID = 'FIREBASE_GET_BY_ID',
    CREATE = 'FIREBASE_CREATE',
    CREATED = 'FIREBASE_CREATED',
    UPDATE = 'FIREBASE_UPDATE',
    DELETE = 'FIREBASE_DELETE',
    RESTORE = 'FIREBASE_RESTORE',
  }